CREATE TABLE IF NOT EXISTS encryption_keys (
  profile_id INTEGER NOT NULL PRIMARY KEY,
  master_key TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);
