//! Product analytics for the Day One CLI, reporting into Automattic Tracks.
//!
//! Design (see also the project plan):
//!
//! - **Transport** is the Tracks REST endpoint (`src/analytics/tracks.rs`),
//!   `POST /rest/v1.1/tracks/record`, which the whole local queue is drained
//!   into as a single batched request per flush. Events are prefixed
//!   `dayone_cli_`.
//! - **Durability** comes from a local SQLite queue: handlers [`track`] events
//!   (a cheap insert), and a best-effort [`flush`] drains the queue at the end
//!   of each invocation. The flush is awaited but tightly time-bounded (see
//!   [`FLUSH_BUDGET`]), so analytics adds at most one request timeout to a
//!   command and never fails one; whatever does not drain in that window is
//!   retried on the next invocation.
//! - **Identity** is always the install-level anonymous id (`_ut = anon`),
//!   before *and* after sign-in. CLI telemetry is deliberately never tied to
//!   the Day One account: the user id is not used as the Tracks identity and no
//!   `_aliasUser` event is emitted. Sign-in state is surfaced only as the
//!   `is_signed_in` event property (see [`identify_on_login`]).
//! - **Scope and opt-out** limit real Tracks delivery to the production Day One
//!   API. `DAYONE_TRACKS_ENDPOINT` explicitly enables local or test delivery for
//!   other API environments. Runtime opt-outs (`DO_NOT_TRACK`,
//!   `DAYONE_TELEMETRY`) and the server-side `track_usage_statistics` account
//!   setting still apply.
//!
//! All public entry points are no-ops when analytics is disabled or the
//! profile database is missing, so callers never need to branch on state.

use std::path::Path;
use std::sync::{Mutex, OnceLock};
use std::time::Duration;

use futures_util::future::join_all;
use serde_json::{Map, Value, json};

use crate::config::AppConfig;
use crate::store::sqlite::Store;

pub mod events;
mod identity;
pub(crate) mod tracks;

pub use events::Event;

use identity::Identity;
use tracks::{EventSender, TracksSender};

/// Maximum number of events sent in a single flush, bounding worst-case time.
const MAX_FLUSH_PER_RUN: usize = 50;

/// Drop events that have failed to send this many times.
const MAX_SEND_ATTEMPTS: i64 = 6;

/// Discard queued events older than this on flush.
const RETENTION_MS: i64 = 30 * 24 * 60 * 60 * 1000;

/// Overall flush budget so analytics never noticeably delays process exit. Set
/// to one per-request timeout ([`tracks::REQUEST_TIMEOUT`]) plus a small margin
/// so a stalled request hits its own timeout — and gets its attempt counted or
/// dropped inside `drain_queue` — before the outer [`tokio::time::timeout`]
/// cancels the drain mid-row (which would otherwise let the same row retry
/// forever). The durable queue drains anything left over on the next run.
const FLUSH_BUDGET: Duration = tracks::REQUEST_TIMEOUT.saturating_add(Duration::from_millis(500));

/// Process-global analytics state, initialised once per invocation by
/// [`init`]. Absent (or `enabled == false`) means every entry point no-ops.
struct State {
    enabled: bool,
    app_version: &'static str,
    os: String,
    identity: Mutex<Identity>,
}

static STATE: OnceLock<State> = OnceLock::new();

/// Initialise analytics for this invocation: resolve the install-level
/// anonymous id (generating and persisting one on first run), derive identity
/// from any stored session, and compute the opt-out gate.
pub fn init(config_dir: &Path, config: &mut AppConfig, store: &Store, base_url: &str) {
    let anon_id = match config.analytics.anonymous_id.as_deref() {
        // Accept only IDs generated by this client. A hand-edited config value
        // must not become a free-form Tracks identity or alias property.
        Some(existing) if identity::is_valid_anonymous_id(existing.trim()) => {
            existing.trim().to_owned()
        }
        _ => {
            let generated = identity::new_anonymous_id();
            config.analytics.anonymous_id = Some(generated.clone());
            // Best-effort: a failure to persist just means we regenerate next
            // run. Never surface analytics setup errors to the user.
            let _ = config.save(config_dir);
            generated
        }
    };

    let session = store.get_auth_session_for_base_url(base_url).ok().flatten();
    let (signed_in, subscription_level) = match session {
        Some(session) => {
            let user = serde_json::from_str::<Value>(&session.user_json).unwrap_or(Value::Null);
            (
                // We record only whether a session exists, never the user id.
                identity::user_id_from_user_value(&user).is_some(),
                identity::subscription_level_from_user_value(&user),
            )
        }
        None => (false, None),
    };

    let enabled = tracks_enabled_for_api(base_url)
        && crate::telemetry::is_enabled()
        && server_analytics_enabled(store);

    let state = State {
        enabled,
        app_version: env!("CARGO_PKG_VERSION"),
        os: format!("{} {}", std::env::consts::OS, std::env::consts::ARCH),
        identity: Mutex::new(Identity {
            signed_in,
            anon_id,
            subscription_level,
        }),
    };
    // Ignore a double-init (only happens in tests that call run() twice in the
    // same process); the first state wins.
    let _ = STATE.set(state);
}

/// Enqueue a tracked event. Cheap and infallible from the caller's view.
pub fn track(store: &Store, event: Event, props: &[(&str, Value)]) {
    let Some(state) = enabled_state() else {
        return;
    };
    let full_name = event.full_name();
    if !tracks::is_valid_name(&full_name) {
        return;
    }
    let custom = filter_custom_properties(event, props.iter().map(|(key, value)| (*key, value)));
    enqueue_params(store, state, &full_name, custom);
}

fn filter_custom_properties<'a>(
    event: Event,
    props: impl IntoIterator<Item = (&'a str, &'a Value)>,
) -> Map<String, Value> {
    let mut custom = Map::new();
    let mut rejected = 0usize;
    for (key, value) in props {
        if custom_property_allowed(event, key, value) {
            custom.insert(key.to_owned(), value.clone());
        } else {
            rejected += 1;
        }
    }
    if rejected > 0 {
        warn_rejected_properties(event, rejected);
    }
    custom
}

fn custom_property_allowed(event: Event, key: &str, value: &Value) -> bool {
    match (event, key) {
        (Event::CommandRun, "command") => value.as_str().is_some_and(is_known_command),
        (Event::CommandRun, "subcommand") => value.as_str().is_some_and(is_known_subcommand),
        (Event::CommandRun, "outcome") => value
            .as_str()
            .is_some_and(|value| matches!(value, "success" | "user_error" | "error")),
        (Event::CommandRun, "duration_ms") => value.as_i64().is_some_and(|value| value >= 0),
        (Event::JournalCreate, "shared" | "encrypted")
        | (Event::EntryCreate | Event::EntryEditFinish, "synced") => value.is_boolean(),
        _ => false,
    }
}

fn is_known_command(value: &str) -> bool {
    matches!(
        value,
        "setup"
            | "auth"
            | "user-settings"
            | "profile"
            | "journal"
            | "entry"
            | "embeddings"
            | "daily-chat"
            | "memory"
            | "context-item"
            | "comment"
            | "list"
            | "search"
            | "sync"
            | "outbox"
            | "sync-schedule"
            | "tui"
            | "doctor"
    )
}

fn is_known_subcommand(value: &str) -> bool {
    matches!(
        value,
        "login"
            | "logout"
            | "key-set"
            | "whoami"
            | "get"
            | "set"
            | "create"
            | "update"
            | "write"
            | "read"
            | "delete"
            | "recalculate-entries"
            | "add"
            | "process"
            | "put"
            | "react"
            | "unreact"
            | "journals"
            | "entries"
            | "daily-chat"
            | "daily-chat-messages"
            | "context-items"
            | "clear"
            | "status"
            | "enable"
            | "set-interval"
            | "disable"
    )
}

fn warn_rejected_properties(event: Event, count: usize) {
    crate::diagnostics::record_analytics_rejection(event.as_str(), count);
    #[cfg(debug_assertions)]
    {
        use std::io::Write as _;
        let _ = writeln!(
            std::io::stderr().lock(),
            "Internal analytics warning: dropped {count} disallowed properties for {}",
            event.as_str()
        );
    }
}

/// Fire the once-per-invocation command-lifecycle event.
pub fn record_command_run(
    store: &Store,
    command: &str,
    subcommand: Option<&str>,
    result: &anyhow::Result<()>,
    duration: Duration,
) {
    let outcome = match result {
        Ok(()) => "success",
        Err(err) if crate::telemetry::is_user_error(err) => "user_error",
        Err(_) => "error",
    };
    let duration_ms = i64::try_from(duration.as_millis()).unwrap_or(i64::MAX);
    let mut props: Vec<(&str, Value)> = vec![
        ("command", json!(command)),
        ("outcome", json!(outcome)),
        ("duration_ms", json!(duration_ms)),
    ];
    if let Some(subcommand) = subcommand {
        props.push(("subcommand", json!(subcommand)));
    }
    track(store, Event::CommandRun, &props);
}

/// Update the in-memory identity on login so events emitted later in this
/// invocation carry `is_signed_in = true` and the subscription tier.
///
/// Unlike Day One Web's `identifyUser`, this deliberately does **not** switch
/// the Tracks identity to the Day One user id or emit an `_aliasUser` event:
/// CLI telemetry stays attributed to the anonymous install id.
pub fn identify_on_login(user: &Value) {
    let Some(state) = enabled_state() else {
        return;
    };
    if identity::user_id_from_user_value(user).is_none() {
        return;
    }
    let subscription = identity::subscription_level_from_user_value(user);

    let mut identity = match state.identity.lock() {
        Ok(guard) => guard,
        Err(poisoned) => poisoned.into_inner(),
    };
    identity.signed_in = true;
    if subscription.is_some() {
        identity.subscription_level = subscription;
    }
}

/// Drain and send queued events. Best-effort and time-bounded.
pub async fn flush(store: &Store) {
    let Some(state) = enabled_state() else {
        return;
    };
    if !store.db_path().exists() {
        return;
    }
    let Ok(sender) = TracksSender::new() else {
        return;
    };
    let (user_ref, user_type) = {
        let identity = match state.identity.lock() {
            Ok(guard) => guard,
            Err(poisoned) => poisoned.into_inner(),
        };
        identity.tracks_pair()
    };
    let _ = tokio::time::timeout(
        FLUSH_BUDGET,
        drain_queue(store, &sender, &user_ref, user_type),
    )
    .await;
}

/// Returns the global state only when analytics is enabled.
fn enabled_state() -> Option<&'static State> {
    STATE.get().filter(|state| state.enabled)
}

/// Build the full parameter map (globals + custom) and append it to the queue.
fn enqueue_params(store: &Store, state: &State, event_name: &str, custom: Map<String, Value>) {
    // Never recreate a database that a destructive command (e.g. `auth logout
    // --force`) has removed.
    if !store.db_path().exists() {
        return;
    }
    let (is_signed_in, subscription, tracks_ui, tracks_ut) = {
        let identity = match state.identity.lock() {
            Ok(guard) => guard,
            Err(poisoned) => poisoned.into_inner(),
        };
        let (tracks_ui, tracks_ut) = identity.tracks_pair();
        (
            identity.is_signed_in(),
            identity.subscription_level.clone(),
            tracks_ui,
            tracks_ut,
        )
    };
    let params = build_params(
        event_name,
        is_signed_in,
        state.app_version,
        &state.os,
        subscription.as_deref(),
        custom,
    );
    let Ok(params_json) = serde_json::to_string(&params) else {
        return;
    };
    let _ = store.enqueue_analytics_event(
        event_name,
        &params_json,
        crate::util::now_epoch_ms(),
        Some(&tracks_ui),
        Some(tracks_ut),
    );
}

/// Assemble the event parameter map: the event name (`_en`), the global
/// properties attached to every event, and the caller's custom properties.
fn build_params(
    event_name: &str,
    is_signed_in: bool,
    app_version: &str,
    os: &str,
    subscription_level: Option<&str>,
    custom: Map<String, Value>,
) -> Map<String, Value> {
    let mut params = Map::new();
    params.insert("_en".to_owned(), json!(event_name));
    params.insert("is_signed_in".to_owned(), json!(is_signed_in));
    params.insert("device_info_app_version".to_owned(), json!(app_version));
    params.insert("device_info_os".to_owned(), json!(os));
    if let Some(subscription_level) = subscription_level {
        params.insert("subscription_level".to_owned(), json!(subscription_level));
    }
    for (key, value) in custom {
        // Never let caller-supplied properties clobber a reserved/global key
        // (the event name, identity flags, or device info): a caller mistake
        // or refactor must not be able to rename the event or flip identity.
        params.entry(key).or_insert(value);
    }
    params
}

struct PendingBatch {
    tracks_ui: String,
    tracks_ut: String,
    events: Vec<Value>,
    rows: Vec<(i64, i64)>,
}

/// Core send routine, parameterised over the sender so it can be unit-tested
/// without the network. Events are grouped by their enqueue-time anonymous
/// identity; rows without a (still-valid, anonymous) identity — including
/// legacy rows stamped with a `dayone:user_id` from an older client — fall back
/// to the current anonymous identity, so nothing is ever sent tied to the
/// account.
async fn drain_queue<S: EventSender>(store: &Store, sender: &S, user_ref: &str, user_type: &str) {
    let cutoff = crate::util::now_epoch_ms().saturating_sub(RETENTION_MS);
    let _ = store.prune_analytics_events_older_than(cutoff);

    let rows = match store.take_analytics_events(MAX_FLUSH_PER_RUN) {
        Ok(rows) => rows,
        Err(_) => return,
    };

    let mut batches: Vec<PendingBatch> = Vec::new();
    // Unparseable rows are dropped so they never wedge the queue.
    let mut to_delete: Vec<i64> = Vec::new();
    for row in rows {
        match build_event_object(&row.params_json, row.created_at_ms) {
            Some(event) => {
                let (tracks_ui, tracks_ut) =
                    queued_identity(&row.tracks_ui, &row.tracks_ut, user_ref, user_type);
                let batch = batches
                    .iter_mut()
                    .find(|batch| batch.tracks_ui == tracks_ui && batch.tracks_ut == tracks_ut);
                if let Some(batch) = batch {
                    batch.events.push(event);
                    batch.rows.push((row.id, row.attempts));
                } else {
                    batches.push(PendingBatch {
                        tracks_ui,
                        tracks_ut,
                        events: vec![event],
                        rows: vec![(row.id, row.attempts)],
                    });
                }
            }
            None => to_delete.push(row.id),
        }
    }
    if batches.is_empty() {
        let _ = store.delete_analytics_events(&to_delete);
        return;
    }

    let mut to_bump: Vec<i64> = Vec::new();
    let results = join_all(batches.into_iter().map(|batch| async move {
        let body = build_batch_body(&batch.tracks_ui, &batch.tracks_ut, batch.events);
        (batch.rows, sender.send(&body).await)
    }))
    .await;
    for (pending, result) in results {
        match result {
            Ok(()) => to_delete.extend(pending.into_iter().map(|(id, _)| id)),
            Err(_) => {
                for (id, attempts) in pending {
                    // Drop rows that have exhausted their retries; otherwise
                    // bump their attempt count so they age out eventually.
                    if attempts + 1 >= MAX_SEND_ATTEMPTS {
                        to_delete.push(id);
                    } else {
                        to_bump.push(id);
                    }
                }
            }
        }
    }
    // Apply all cleanup with at most one bulk delete and one bulk update,
    // instead of opening a fresh SQLite connection per row.
    let _ = store.delete_analytics_events(&to_delete);
    let _ = store.bump_analytics_event_attempts(&to_bump);
}

fn queued_identity(
    tracks_ui: &Option<String>,
    tracks_ut: &Option<String>,
    fallback_ui: &str,
    fallback_ut: &str,
) -> (String, String) {
    match (tracks_ui.as_deref(), tracks_ut.as_deref()) {
        (Some(ui), Some(identity::USER_ID_TYPE_ANON)) if identity::is_valid_anonymous_id(ui) => {
            (ui.to_owned(), identity::USER_ID_TYPE_ANON.to_owned())
        }
        // Anything else — no identity, or a legacy `dayone:user_id` row from an
        // older client — is anonymized to the current fallback identity.
        _ => (fallback_ui.to_owned(), fallback_ut.to_owned()),
    }
}

/// Turn a stored event into a Tracks `events[]` entry: the event's stored
/// properties (stringified, matching Tracks' string-valued schema) plus its
/// original event time (`_ts`).
///
/// Defensive against corrupted or hand-edited queue rows: the event is dropped
/// (returns `None`) when `_en` is missing or not a valid Tracks name, and any
/// individual property whose key is invalid is skipped — so one bad key can
/// never get the whole event rejected by the Tracks ETL.
pub(crate) fn build_event_object(params_json: &str, created_at_ms: i64) -> Option<Value> {
    let value = serde_json::from_str::<Value>(params_json).ok()?;
    let object = value.as_object()?;

    let event_name = object.get("_en").and_then(Value::as_str)?;
    // Legacy `_aliasUser` rows queued by an older client are dropped: the CLI no
    // longer links the anonymous id to the account.
    let analytics_event = event_from_full_name(event_name)?;
    let custom = filter_custom_properties(
        analytics_event,
        object
            .iter()
            .filter(|(key, _)| !is_global_property(key))
            .map(|(key, value)| (key.as_str(), value)),
    );

    let is_signed_in = object.get("is_signed_in").and_then(Value::as_bool)?;
    let mut event = Map::with_capacity(custom.len() + 6);
    event.insert("_en".to_owned(), json!(event_name));
    event.insert("is_signed_in".to_owned(), json!(is_signed_in.to_string()));
    event.insert(
        "device_info_app_version".to_owned(),
        json!(env!("CARGO_PKG_VERSION")),
    );
    event.insert(
        "device_info_os".to_owned(),
        json!(format!(
            "{} {}",
            std::env::consts::OS,
            std::env::consts::ARCH
        )),
    );
    if let Some(subscription_level) = object
        .get("subscription_level")
        .and_then(Value::as_str)
        .and_then(identity::normalize_subscription_level)
    {
        event.insert("subscription_level".to_owned(), json!(subscription_level));
    }
    for (key, value) in custom {
        event.insert(key, json!(value_to_query_string(&value)));
    }
    event.insert("_ts".to_owned(), json!(created_at_ms.to_string()));
    Some(Value::Object(event))
}

fn event_from_full_name(name: &str) -> Option<Event> {
    Event::ALL
        .iter()
        .copied()
        .find(|event| event.full_name() == name)
}

fn is_global_property(key: &str) -> bool {
    matches!(
        key,
        "_en"
            | "is_signed_in"
            | "device_info_app_version"
            | "device_info_os"
            | "subscription_level"
    )
}

/// Assemble the `tracks/record` request body: identity in `commonProps`
/// (`_ui`/`_ut`) plus the per-batch request time (`_rt`), and the events array.
pub(crate) fn build_batch_body(user_ref: &str, user_type: &str, events: Vec<Value>) -> Value {
    json!({
        "commonProps": {
            "_ui": user_ref,
            "_ut": user_type,
            "_rt": crate::util::now_epoch_ms_string(),
        },
        "events": events,
    })
}

/// Render a JSON value as a flat Tracks string value (Tracks stores event
/// properties as strings, so we stringify scalars rather than send typed JSON).
fn value_to_query_string(value: &Value) -> String {
    match value {
        Value::String(string) => string.clone(),
        Value::Bool(boolean) => boolean.to_string(),
        Value::Number(number) => number.to_string(),
        Value::Null => String::new(),
        other => other.to_string(),
    }
}

fn tracks_enabled_for_api(base_url: &str) -> bool {
    crate::diagnostics::endpoint_class(base_url) == "production" || tracks::endpoint_overridden()
}

/// Honour the server-side analytics opt-out. Defaults to enabled when the
/// setting is absent or unparseable, matching Day One Web.
fn server_analytics_enabled(store: &Store) -> bool {
    let Ok(Some(data_json)) = store.get_user_settings_data_json() else {
        return true;
    };
    let Ok(value) = serde_json::from_str::<Value>(&data_json) else {
        return true;
    };
    if let Some(enabled) = find_bool(&value, "track_usage_statistics") {
        return enabled;
    }
    if let Some(opt_out) = find_bool(&value, "analytics_opt_out") {
        return !opt_out;
    }
    true
}

/// Shallow recursive search for the first boolean value stored under `key`
/// anywhere in the settings object tree.
fn find_bool(value: &Value, key: &str) -> Option<bool> {
    match value {
        Value::Object(map) => {
            if let Some(Value::Bool(found)) = map.get(key) {
                return Some(*found);
            }
            map.values().find_map(|child| find_bool(child, key))
        }
        Value::Array(items) => items.iter().find_map(|child| find_bool(child, key)),
        _ => None,
    }
}

#[cfg(test)]
mod tests;
